# Generated by Django 4.0.4 on 2023-06-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageClassificationModel',
        ),
    ]
